import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius } from '@/src/constants/theme';

export const createStyles = (theme: any) => StyleSheet.create({
    card: {
        marginBottom: Spacing.md,
        overflow: 'hidden',
        borderLeftWidth: 4,
        borderRadius: BorderRadius.lg,
        backgroundColor: theme.cardBackground,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: Spacing.md,
        paddingVertical: Spacing.md + 2,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        flex: 1,
        gap: Spacing.md,
    },
    iconContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 2,
    },
    headerContent: {
        flex: 1,
        justifyContent: 'center',
    },
    metaText: {
        fontSize: 12,
        marginBottom: 2,
    },
    title: {
        fontSize: 16,
        lineHeight: 22,
    },
    content: {
        paddingHorizontal: Spacing.md,
        paddingBottom: Spacing.md,
    },
    description: {
        marginBottom: Spacing.md,
        lineHeight: 20,
        fontSize: 14,
    },
    actionRow: {
        flexDirection: 'row',
        gap: Spacing.sm,
        marginBottom: Spacing.md,
    },
    statusButton: {
        flex: 1,
        aspectRatio: 1.2,
        alignItems: 'center',
        justifyContent: 'center',
        padding: Spacing.sm,
        borderRadius: BorderRadius.md,
        borderWidth: 1,
        backgroundColor: theme.cardBackground,
        gap: 8,
    },
    statusButtonText: {
        fontSize: 12,
        textAlign: 'center',
    },
    utilityRow: {
        flexDirection: 'row',
        gap: Spacing.sm,
        marginBottom: Spacing.md,
    },
    utilityButton: {
        flex: 1,
        height: 48,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: BorderRadius.md,
        borderWidth: 1,
        borderColor: theme.border,
        backgroundColor: theme.cardBackground,
    },
    submitButton: {
        backgroundColor: theme.primary,
        borderRadius: BorderRadius.md,
        height: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
    },
    statusChip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: Spacing.sm,
        paddingVertical: Spacing.xs,
        borderRadius: BorderRadius.sm,
        gap: 4,
        alignSelf: 'flex-start',
        marginTop: 4,
    },
    photoThumbnail: {
        width: 60,
        height: 60,
        borderRadius: BorderRadius.sm,
        marginRight: Spacing.xs,
    },
    inputField: {
        borderWidth: 1,
        borderRadius: BorderRadius.md,
        padding: Spacing.sm,
        minHeight: 80,
        textAlignVertical: 'top',
        fontSize: 14,
        marginBottom: Spacing.sm,
    },
    videoPlaceholder: {
        backgroundColor: '#000',
        justifyContent: 'center',
        alignItems: 'center',
    },
    videoLabel: {
        position: 'absolute',
        bottom: 2,
        fontSize: 8,
        fontWeight: '700',
    },
    completedBadge: {
        backgroundColor: theme.success + '20',
        borderColor: theme.success,
        borderWidth: 1,
        borderRadius: BorderRadius.sm,
        paddingHorizontal: Spacing.sm,
        paddingVertical: 2,
        alignSelf: 'flex-start',
    },
});
