# Generated by Django 5.2.10 on 2026-01-12 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('ORGANIZATION', 'Organization'), ('PROCEDURE', 'Procedure'), ('COMPLIANCE', 'Compliance')], max_length=50)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('triggered_by', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled')], max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_procedures', models.PositiveIntegerField(default=0)),
                ('completed_procedures', models.PositiveIntegerField(default=0)),
                ('pending_procedures', models.PositiveIntegerField(default=0)),
                ('non_compliance_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='organizations.department')),
                ('generated_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('portal', 'Portal')], default='portal', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='reporting.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Distribution',
                'verbose_name_plural': 'Report Distributions',
                'db_table': 'report_distributions',
                'ordering': ['-distributed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('report_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('ORGANIZATION', 'Organization'), ('PROCEDURE', 'Procedure'), ('COMPLIANCE', 'Compliance')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('trigger_day_of_month', models.PositiveSmallIntegerField(default=1)),
                ('trigger_hour', models.PositiveSmallIntegerField(default=0)),
                ('trigger_minute', models.PositiveSmallIntegerField(default=0)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('recipient_email_list', models.JSONField(default=list)),
                ('should_notify_department_head', models.BooleanField(default=True)),
                ('should_notify_compliance_officer', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'db_table': 'report_schedules',
                'ordering': ['next_run'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'status'], name='reports_organiz_1556f6_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['department', 'status'], name='reports_departm_f62ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='reports_report__f9d8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['period_year', 'period_month'], name='reports_period__13b8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdistribution',
            index=models.Index(fields=['report', 'user'], name='report_dist_report__df13e5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdistribution',
            index=models.Index(fields=['status'], name='report_dist_status_1b9197_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['organization', 'is_active'], name='report_sche_organiz_41ad8d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['next_run', 'is_active'], name='report_sche_next_ru_09abbf_idx'),
        ),
    ]
