# Generated by Django 5.2.10 on 2026-01-31 00:25

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.utils.get_organization_upload_path),
        ),
    ]
