# Generated by Django 5.2.10 on 2026-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdistribution',
            name='delivery_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('PORTAL', 'Portal')], default='PORTAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportdistribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20),
        ),
    ]
