# Generated by Django 5.2.10 on 2026-01-12 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('entities', '0001_initial'),
        ('execution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PROCEDURE_DUE', 'Procedure Due'), ('PROCEDURE_OVERDUE', 'Procedure Overdue'), ('NON_COMPLIANCE_REPORTED', 'Non-Compliance Reported'), ('NON_COMPLIANCE_ASSIGNED', 'Non-Compliance Assigned'), ('NON_COMPLIANCE_RESOLVED', 'Non-Compliance Resolved'), ('ENTITY_SHARED', 'Entity Shared'), ('PROCEDURE_SHARED', 'Procedure Shared'), ('SYSTEM', 'System')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.noncomplianceissue')),
                ('procedure_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='execution.procedurelog')),
                ('step_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='execution.steplog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'type'], name='notificatio_user_id_6b5847_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_cb6908_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=500)),
                ('device_type', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=50, null=True)),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Token',
                'verbose_name_plural': 'Push Tokens',
                'db_table': 'push_tokens',
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='push_tokens_user_id_3067f6_idx'), models.Index(fields=['token'], name='push_tokens_token_c43621_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'token'), name='unique_user_token')],
            },
        ),
    ]
