# Generated by Django 5.2.10 on 2026-01-21 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('execution', '0002_reminder'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROCEDURE_DUE', 'Procedure Due'), ('PROCEDURE_OVERDUE', 'Procedure Overdue'), ('STEP_OVERDUE', 'Step Overdue'), ('NON_COMPLIANCE_REPORTED', 'Non-Compliance Reported'), ('NON_COMPLIANCE_ASSIGNED', 'Non-Compliance Assigned'), ('NON_COMPLIANCE_RESOLVED', 'Non-Compliance Resolved'), ('NON_COMPLIANCE_OVERDUE', 'Non-Compliance Overdue'), ('HELP_REQUEST_RECEIVED', 'Help Request Received'), ('HELP_REQUEST_RESPONDED', 'Help Request Responded'), ('ENTITY_SHARED', 'Entity Shared'), ('PROCEDURE_SHARED', 'Procedure Shared'), ('ASSIGNMENT_NEW', 'New Assignment'), ('ASSIGNMENT_UPDATED', 'Assignment Updated'), ('SYSTEM', 'System')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure_due_enabled', models.BooleanField(default=True)),
                ('procedure_overdue_enabled', models.BooleanField(default=True)),
                ('issue_enabled', models.BooleanField(default=True)),
                ('help_request_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('reminder_days_before', models.PositiveIntegerField(default=3)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('notification_type', models.CharField(choices=[('PROCEDURE_DUE', 'Procedure Due'), ('PROCEDURE_OVERDUE', 'Procedure Overdue'), ('STEP_OVERDUE', 'Step Overdue'), ('NON_COMPLIANCE_REPORTED', 'Non-Compliance Reported'), ('NON_COMPLIANCE_ASSIGNED', 'Non-Compliance Assigned'), ('NON_COMPLIANCE_RESOLVED', 'Non-Compliance Resolved'), ('NON_COMPLIANCE_OVERDUE', 'Non-Compliance Overdue'), ('HELP_REQUEST_RECEIVED', 'Help Request Received'), ('HELP_REQUEST_RESPONDED', 'Help Request Responded'), ('ENTITY_SHARED', 'Entity Shared'), ('PROCEDURE_SHARED', 'Procedure Shared'), ('ASSIGNMENT_NEW', 'New Assignment'), ('ASSIGNMENT_UPDATED', 'Assignment Updated'), ('SYSTEM', 'System')], max_length=50)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_send_at', models.DateTimeField(db_index=True)),
                ('repeat_interval_hours', models.PositiveIntegerField(default=24)),
                ('send_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('target_completed', models.BooleanField(default=False)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance.noncomplianceissue')),
                ('procedure_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='execution.procedurelog')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_schedules',
                'ordering': ['next_send_at'],
                'indexes': [models.Index(fields=['is_active', 'next_send_at'], name='notificatio_is_acti_e4e0c3_idx'), models.Index(fields=['notification_type', 'is_active'], name='notificatio_notific_a47624_idx'), models.Index(fields=['target_user', 'is_active'], name='notificatio_target__b3036b_idx')],
            },
        ),
    ]
