# Generated by Django 5.2.10 on 2026-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type_notificationpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_persistent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
