# Generated by Django 5.2.10 on 2026-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_is_persistent_to_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='device_type',
            field=models.CharField(blank=True, choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WEB', 'Web')], max_length=50, null=True),
        ),
    ]
