# Generated by Django 5.2.10 on 2026-03-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROCEDURE_DUE', 'Procedure Due'), ('PROCEDURE_OVERDUE', 'Procedure Overdue'), ('STEP_OVERDUE', 'Step Overdue'), ('NON_COMPLIANCE_REPORTED', 'Non-Compliance Reported'), ('NON_COMPLIANCE_ASSIGNED', 'Non-Compliance Assigned'), ('NON_COMPLIANCE_RESOLVED', 'Non-Compliance Resolved'), ('NON_COMPLIANCE_OVERDUE', 'Non-Compliance Overdue'), ('HELP_REQUEST_RECEIVED', 'Help Request Received'), ('HELP_REQUEST_RESPONDED', 'Help Request Responded'), ('NON_COMPLIANCE_COMMENT', 'Non-Compliance Comment'), ('NON_COMPLIANCE_STATUS_CHANGED', 'Non-Compliance Status Changed'), ('ENTITY_SHARED', 'Entity Shared'), ('PROCEDURE_SHARED', 'Procedure Shared'), ('ASSIGNMENT_NEW', 'New Assignment'), ('ASSIGNMENT_UPDATED', 'Assignment Updated'), ('SYSTEM', 'System')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='notification_type',
            field=models.CharField(choices=[('PROCEDURE_DUE', 'Procedure Due'), ('PROCEDURE_OVERDUE', 'Procedure Overdue'), ('STEP_OVERDUE', 'Step Overdue'), ('NON_COMPLIANCE_REPORTED', 'Non-Compliance Reported'), ('NON_COMPLIANCE_ASSIGNED', 'Non-Compliance Assigned'), ('NON_COMPLIANCE_RESOLVED', 'Non-Compliance Resolved'), ('NON_COMPLIANCE_OVERDUE', 'Non-Compliance Overdue'), ('HELP_REQUEST_RECEIVED', 'Help Request Received'), ('HELP_REQUEST_RESPONDED', 'Help Request Responded'), ('NON_COMPLIANCE_COMMENT', 'Non-Compliance Comment'), ('NON_COMPLIANCE_STATUS_CHANGED', 'Non-Compliance Status Changed'), ('ENTITY_SHARED', 'Entity Shared'), ('PROCEDURE_SHARED', 'Procedure Shared'), ('ASSIGNMENT_NEW', 'New Assignment'), ('ASSIGNMENT_UPDATED', 'Assignment Updated'), ('SYSTEM', 'System')], max_length=50),
        ),
    ]
