# Generated by Django 5.2.10 on 2026-01-12 12:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('interval_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('interval_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months'), ('YEARS', 'Years')], default='DAYS', max_length=20)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_procedures', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='entities.entity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedures',
                'db_table': 'procedures',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_notes', models.BooleanField(default=False)),
                ('requires_compliance_check', models.BooleanField(default=False)),
                ('expected_duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('reference_images', models.JSONField(blank=True, default=list)),
                ('checklist_items', models.JSONField(blank=True, default=list)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Procedure Step',
                'verbose_name_plural': 'Procedure Steps',
                'db_table': 'procedure_steps',
                'ordering': ['procedure', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('template_data', models.JSONField()),
                ('is_public', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_templates', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Procedure Template',
                'verbose_name_plural': 'Procedure Templates',
                'db_table': 'procedure_templates',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['organization', 'entity'], name='procedures_organiz_549737_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['priority', 'is_active'], name='procedures_priorit_7e4ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['entity', 'is_active'], name='procedures_entity__1379b0_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurestep',
            index=models.Index(fields=['procedure', 'step_order'], name='procedure_s_procedu_53cec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='procedurestep',
            constraint=models.UniqueConstraint(fields=('procedure', 'step_order'), name='unique_procedure_step_order'),
        ),
        migrations.AddIndex(
            model_name='proceduretemplate',
            index=models.Index(fields=['organization', 'is_public'], name='procedure_t_organiz_ec5f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduretemplate',
            index=models.Index(fields=['category'], name='procedure_t_categor_bf3c46_idx'),
        ),
    ]
