# Generated by Django 5.2.10 on 2026-01-12 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('organizations', '0001_initial'),
        ('procedures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_procedure_date', models.DateField(blank=True, db_index=True, null=True)),
                ('has_unresolved_issues', models.BooleanField(default=False)),
                ('blocked_by_issues', models.BooleanField(default=False)),
                ('blocking_issues_count', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('completed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_procedure_logs', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_logs', to='entities.entity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_logs', to='organizations.organization')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='procedures.procedure')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_procedure_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedure Log',
                'verbose_name_plural': 'Procedure Logs',
                'db_table': 'procedure_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('procedure_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='execution.procedurelog')),
                ('shared_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_procedure_logs', to='organizations.department')),
            ],
            options={
                'verbose_name': 'Procedure Share',
                'verbose_name_plural': 'Procedure Shares',
                'db_table': 'procedure_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('is_compliant', models.BooleanField(default=True)),
                ('completion_status', models.CharField(blank=True, max_length=50, null=True)),
                ('has_blocking_issue', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_results', models.JSONField(blank=True, default=dict)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('procedure_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='execution.procedurelog')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='procedures.procedurestep')),
            ],
            options={
                'verbose_name': 'Step Log',
                'verbose_name_plural': 'Step Logs',
                'db_table': 'step_logs',
                'ordering': ['procedure_log', 'step__step_order'],
            },
        ),
        migrations.CreateModel(
            name='StepReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remind_at', models.DateTimeField(db_index=True)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('procedure_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_reminders', to='execution.procedurelog')),
                ('step_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='execution.steplog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Step Reminder',
                'verbose_name_plural': 'Step Reminders',
                'db_table': 'step_reminders',
                'ordering': ['remind_at'],
            },
        ),
        migrations.AddIndex(
            model_name='procedurelog',
            index=models.Index(fields=['status', 'organization'], name='procedure_l_status_5ac234_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurelog',
            index=models.Index(fields=['next_procedure_date'], name='procedure_l_next_pr_d5ef7e_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurelog',
            index=models.Index(fields=['entity', 'status'], name='procedure_l_entity__d414f1_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurelog',
            index=models.Index(fields=['procedure', 'status'], name='procedure_l_procedu_c70879_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurelog',
            index=models.Index(fields=['user', 'status'], name='procedure_l_user_id_c3c5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='procedureshare',
            index=models.Index(fields=['procedure_log', 'is_active'], name='procedure_s_procedu_c3f081_idx'),
        ),
        migrations.AddIndex(
            model_name='procedureshare',
            index=models.Index(fields=['shared_with_department', 'is_active'], name='procedure_s_shared__ded7ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='procedureshare',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('procedure_log', 'shared_with_department'), name='unique_active_procedure_share'),
        ),
        migrations.AddIndex(
            model_name='steplog',
            index=models.Index(fields=['procedure_log', 'is_completed'], name='step_logs_procedu_5b4006_idx'),
        ),
        migrations.AddIndex(
            model_name='steplog',
            index=models.Index(fields=['step', 'is_completed'], name='step_logs_step_id_c9c023_idx'),
        ),
        migrations.AddIndex(
            model_name='steplog',
            index=models.Index(fields=['completed_by_user'], name='step_logs_complet_8f0b20_idx'),
        ),
        migrations.AddIndex(
            model_name='stepreminder',
            index=models.Index(fields=['user', 'is_sent'], name='step_remind_user_id_e92556_idx'),
        ),
        migrations.AddIndex(
            model_name='stepreminder',
            index=models.Index(fields=['remind_at', 'is_sent'], name='step_remind_remind__7f70b0_idx'),
        ),
    ]
