# Generated by Django 5.2.10 on 2026-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_update_status_to_lowercase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurelog',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=20),
        ),
    ]
