# Generated by Django 5.2.10 on 2026-02-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role', 'is_active'], name='user_org_role_active_idx'),
        ),
    ]
