# Generated by Django 5.2.10 on 2026-01-12 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('procedures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_reason', models.TextField(blank=True, null=True)),
                ('assignment_notes', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('recurring', models.BooleanField(default=False)),
                ('assigned_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_assignments', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='procedures.procedure')),
            ],
            options={
                'verbose_name': 'Procedure Assignment',
                'verbose_name_plural': 'Procedure Assignments',
                'db_table': 'procedure_assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to_user', 'status'], name='procedure_a_assigne_5be0c8_idx'), models.Index(fields=['procedure', 'assigned_to_user'], name='procedure_a_procedu_eb95a6_idx'), models.Index(fields=['status', 'is_active'], name='procedure_a_status_1f5244_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(db_index=True, max_length=50)),
                ('permissions', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('configured_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_configs', to='organizations.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_configs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Role Permission Config',
                'verbose_name_plural': 'Role Permission Configs',
                'db_table': 'role_permission_configs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'role', 'is_active'], name='role_permis_organiz_4682c4_idx'), models.Index(fields=['department', 'role', 'is_active'], name='role_permis_departm_7725e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('PROCEDURE', 'Procedure'), ('ENTITY', 'Entity'), ('DEPARTMENT', 'Department'), ('ORGANIZATION', 'Organization'), ('USER', 'User'), ('ISSUE', 'Issue'), ('ASSIGNMENT', 'Assignment')], db_index=True, max_length=50)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign'), ('APPROVE', 'Approve'), ('RESOLVE', 'Resolve')], max_length=20)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('OWN', 'Own'), ('DEPARTMENT', 'Department'), ('ORGANIZATION', 'Organization'), ('ALL', 'All')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('granted_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'db_table': 'user_permissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'resource_type', 'action'], name='user_permis_user_id_e300dd_idx'), models.Index(fields=['user', 'is_active'], name='user_permis_user_id_637b6a_idx'), models.Index(fields=['scope'], name='user_permis_scope_a5aa3b_idx')],
            },
        ),
    ]
