# Generated by Django 5.2.10 on 2026-01-19 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rolepermissionconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('organization', 'role'), name='unique_org_role_config'),
        ),
        migrations.AddConstraint(
            model_name='rolepermissionconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('department', 'role'), name='unique_dept_role_config'),
        ),
    ]
