# Generated by Django 5.2.10 on 2026-02-11 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('permissions', '0002_rolepermissionconfig_unique_org_role_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('WORKER', 'Worker')], db_index=True, max_length=50)),
                ('permissions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_permission_policies', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_policies', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_policies', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Permission Policy',
                'verbose_name_plural': 'Permission Policies',
                'db_table': 'permission_policies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'role', 'is_active'], name='permission__organiz_559082_idx'), models.Index(fields=['department', 'role', 'is_active'], name='permission__departm_defafd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('is_active', True)), fields=('organization', 'role'), name='unique_active_org_role_policy'), models.UniqueConstraint(condition=models.Q(('department__isnull', False), ('is_active', True)), fields=('department', 'role'), name='unique_active_dept_role_policy')],
            },
        ),
    ]
