# Generated by Django 5.2.10 on 2026-01-12 12:50

import apps.entities.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('qr_code', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(db_index=True, default='active', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'db_table': 'entities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='entity_documents/')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('manual', 'Manual'), ('certificate', 'Certificate'), ('warranty', 'Warranty'), ('invoice', 'Invoice'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Entity Document',
                'verbose_name_plural': 'Entity Documents',
                'db_table': 'entity_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='entity_images/', validators=[apps.entities.models.validate_image_size, apps.entities.models.validate_image_extension])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='entity_images/thumbnails/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Entity Image',
                'verbose_name_plural': 'Entity Images',
                'db_table': 'entity_images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='entities.entity')),
                ('shared_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_entities', to='organizations.department')),
            ],
            options={
                'verbose_name': 'Entity Share',
                'verbose_name_plural': 'Entity Shares',
                'db_table': 'entity_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['qr_code'], name='entities_qr_code_a987f1_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entity_type'], name='entities_entity__d2e80f_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['organization', 'department'], name='entities_organiz_f1f4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['status'], name='entities_status_1c41cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_org_entity_code'),
        ),
        migrations.AddIndex(
            model_name='entitydocument',
            index=models.Index(fields=['entity', 'document_type'], name='entity_docu_entity__94435f_idx'),
        ),
        migrations.AddIndex(
            model_name='entityimage',
            index=models.Index(fields=['entity', 'is_primary'], name='entity_imag_entity__1ffef1_idx'),
        ),
        migrations.AddIndex(
            model_name='entityimage',
            index=models.Index(fields=['entity', 'order'], name='entity_imag_entity__ae379b_idx'),
        ),
        migrations.AddIndex(
            model_name='entityshare',
            index=models.Index(fields=['entity', 'is_active'], name='entity_shar_entity__20cfa0_idx'),
        ),
        migrations.AddIndex(
            model_name='entityshare',
            index=models.Index(fields=['shared_with_department', 'is_active'], name='entity_shar_shared__368ff4_idx'),
        ),
        migrations.AddConstraint(
            model_name='entityshare',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('entity', 'shared_with_department'), name='unique_active_entity_share'),
        ),
    ]
