# Generated by Django 5.2.10 on 2026-01-15 21:30

import apps.entities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydocument',
            name='file',
            field=models.FileField(upload_to='entity_documents/', validators=[apps.entities.models.validate_document_extension]),
        ),
    ]
