# Generated by Django 5.2.10 on 2026-01-31 00:25

import apps.core.utils
import apps.entities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_entitydocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.get_organization_upload_path),
        ),
        migrations.AlterField(
            model_name='entitydocument',
            name='file',
            field=models.FileField(upload_to=apps.core.utils.get_organization_upload_path, validators=[apps.entities.models.validate_document_extension]),
        ),
        migrations.AlterField(
            model_name='entityimage',
            name='image',
            field=models.ImageField(upload_to=apps.core.utils.get_organization_upload_path, validators=[apps.entities.models.validate_image_size, apps.entities.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='entityimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.get_organization_upload_path),
        ),
    ]
