# Generated by Django 5.2.10 on 2026-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_entity_qr_image_alter_entitydocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='entitydocument',
            name='document_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('CERTIFICATE', 'Certificate'), ('WARRANTY', 'Warranty'), ('INVOICE', 'Invoice'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
