# Generated by Django 5.2.10 on 2026-02-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_company_623a02_idx',
            old_name='organizations_company_0e1f2a_idx',
        ),
    ]
