# Generated by Django 6.0.3 on 2026-03-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_rename_organizations_company_0e1f2a_idx_organizatio_company_623a02_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_sandbox',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
