# Generated by Django 5.2.10 on 2026-01-12 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('execution', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonComplianceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('VERIFIED', 'Verified'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('resolution_photo_urls', models.JSONField(blank=True, default=list)),
                ('resolved_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('assigned_to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='organizations.department')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='entities.entity')),
                ('procedure_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='execution.procedurelog')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('step_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='execution.steplog')),
            ],
            options={
                'verbose_name': 'Non-Compliance Issue',
                'verbose_name_plural': 'Non-Compliance Issues',
                'db_table': 'non_compliance_issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_internal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='compliance.noncomplianceissue')),
            ],
            options={
                'verbose_name': 'Issue Comment',
                'verbose_name_plural': 'Issue Comments',
                'db_table': 'issue_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests_sent', to='organizations.department')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests_created', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests_responded', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests_targeted', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests_received', to='organizations.department')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='compliance.noncomplianceissue')),
            ],
            options={
                'verbose_name': 'Help Request',
                'verbose_name_plural': 'Help Requests',
                'db_table': 'help_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='noncomplianceissue',
            index=models.Index(fields=['status', 'severity'], name='non_complia_status_18af45_idx'),
        ),
        migrations.AddIndex(
            model_name='noncomplianceissue',
            index=models.Index(fields=['entity', 'status'], name='non_complia_entity__7f1be3_idx'),
        ),
        migrations.AddIndex(
            model_name='noncomplianceissue',
            index=models.Index(fields=['assigned_to_department', 'status'], name='non_complia_assigne_e5e544_idx'),
        ),
        migrations.AddIndex(
            model_name='noncomplianceissue',
            index=models.Index(fields=['assigned_to_user', 'status'], name='non_complia_assigne_7a06f1_idx'),
        ),
        migrations.AddIndex(
            model_name='noncomplianceissue',
            index=models.Index(fields=['due_date'], name='non_complia_due_dat_d6ead4_idx'),
        ),
        migrations.AddIndex(
            model_name='issuecomment',
            index=models.Index(fields=['issue', 'created_at'], name='issue_comme_issue_i_937053_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['to_department', 'status'], name='help_reques_to_depa_c0350b_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['from_department', 'status'], name='help_reques_from_de_592be9_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['target_user', 'status'], name='help_reques_target__8b86d5_idx'),
        ),
    ]
